pipeline {
    agent { node { label 'maven' } }
    stages {
        stage('Test') {
            steps {
                sh 'cd calculator-monolith && ./mvnw clean test'
            }
        }
        stage('Build') {
            environment {
                QUAY = credentials('QUAY')
            }
            steps {
                sh './calculator-monolith/scripts/include-container-extensions.sh'

                sh '''
                    calculator-monolith/scripts/build-and-push-image.sh \
                    -b $BUILD_NUMBER \
                    -u "$QUAY_USR" \
                    -p "$QUAY_PSW" \
                    -r do400-monitoring-lab
                '''
            }
        }
    }
}
